#!./bin/python
""" Creates a new python script in the bin folder """

import sys
import common


def usage():
    """ Print the intended usage """
    print(f"{common.f_name} <script-name>")
    sys.exit(1)


if len(sys.argv) < 2:
    usage()

path = f"{common.home}/.local/bin/{sys.argv[1]}"

common.new_script(path)
