#!/usr/bin/env python3
""" Creates a new python script in the bin folder """

import sys
import Common


def usage():
    """ Print the intended usage """
    print(f"{Common.f_name} <script-name>")
    sys.exit(1)


if len(sys.argv) < 2:
    usage()

path = f"{Common.home}/.local/bin/{sys.argv[1]}"

Common.new_script(path)
