#!/bin/env ruby
# frozen_string_literal: true

# $DEBUG = true

def move_file(file, regex, target_dir, prefix)
  match = regex.match(file)
  puts match if defined?($DEBUG)
  target_dir = "#{target_dir}/Season_#{match[1]}"
  `mkdir -p #{target_dir}`
  target = "#{target_dir}/#{prefix}_S#{match[1]}E#{match[2]}.mkv"
  `mv -v #{file} #{target}`
end

def move(regex, target_dir, prefix, *files)
  if files.is_a?(String)
    move_file(files, regex, target_dir, prefix)
  else
    files.each do |file|
      move_file(file, regex, target_dir, prefix)
    end
  end
end

if ARGV.length < 3
  puts "Usage: #{$PROGRAM_NAME} pattern destination prefix files "
else
  ARGV[0] = eval(ARGV[0])
  if defined?($DEBUG) then ARGV.each do |arg|
    puts "#{arg.class}: #{arg}"
  end
  end
  move(*ARGV)
end
