#!/usr/bin/env bash

source ~/.functions.sh

# RE-ENABLE when pulling
# gsync
git branch -r > ~/.branches
nvim ~/.branches +"set filetype=branches"
rm ~/.branches
remote_branch=$(xclip -selection clipboard -o)

# split the branch into different parts
old_ifs=$IFS
IFS='/'
read -ra branch_array <<< $remote_branch

# remove the origin/ part of the branch name
if [[ "${branch_array[0]}" = *"origin"* ]]; then
  branch=${branch_array[1]}
else
  branch=$remote_branch
fi
IFS=' '
echo branch is "$branch"
echo remote_branch is "$remote_branch"

# If the branch is not saved save it and set the upstream
if [[ -z "$(git branch | grep $branch )" ]]; then
  echo saving new branch
  if confirm 'Would you like to overwrite this branch'; then
    echo "OVERWRITING BRANCH"
    git checkout -b $branch
    git add -A
    git commit -a
    git push -uf origin $branch
  else
    git checkout $remote_branch
    git checkout -b $branch
    git push -u origin $branch
  fi
else
  echo checking out existing branch
  git checkout $branch
fi
