#!/usr/bin/env zsh

if [[ $OSTYPE == *darwin* ]]; then
  echo copying key using pbcopy
  cat ~/.ssh/id_rsa.pub | pbcopy
else
  echo copying key with xclip
  cat ~/.ssh/id_rsa.pub | xclip -sel clip
fi
