#!/usr/bin/env zsh

xrandr \
  --output eDP1 --off
xrandr \
  --output HDMI2 --mode 1920x1080 --rate 60 --pos 0x0 --primary \
  --output HDMI1 --mode 1280x720  --rate 60 --pos 1921x360
  # --output HDMI1 --auto --pos 1921x360
