#!/usr/bin/env python3

import sys
import subprocess
import dbus

with subprocess.Popen(
    ['ofono-phonesim', '-p', '12345', '/usr/share/phonesim/default.xml']):
    bus = dbus.SystemBus()

    if len(sys.argv) == 2:
        path = sys.argv[1]
    else:
        manager = dbus.Interface(bus.get_object('org.ofono', '/'),
                                 'org.ofono.Manager')
        modems = manager.GetModems()
        path = modems[0][0]

    print("Connecting modem %s...".format(path))
    modem = dbus.Interface(bus.get_object('org.ofono', path),
                           'org.ofono.Modem')

    modem.SetProperty("Powered", dbus.Boolean(1), timeout=120)
