#!/bin/bash

usage () {
  echo "
  $0: creates a new github project in ~/Projects
  assumes github username is the same as local username: $USER
  $0 <project_name>
  "
  exit 1
}

if [[ -z $1 ]]; then
  usage
fi

mkdir -p ~/Projects
gh repo clone $USER/$1 ~/Projects/$1
cd ~/Projects/$1
git push -u origin master
