#!/bin/bash

usage () {
  echo "$0: creates a new github project in ~/Documents/github/"
  echo "$0 <project_name>"
  exit 1
}

if [[ -z $1 ]]; then
  usage
fi

gh repo clone $USER/$1 ~/Documents/github/$1
cd ~/Documents/github/$1
git push -u origin master
