#!/bin/bash

usage () {
  echo "
  Creates a new public repo in $HOME/Projects/ directory
  assumes gh is logged in.
  $0 <new_repo_name>
  "
  exit 1
}

if [[ -z $1 ]]; then
  usage
fi

mkdir -p ~/Projects/$1
cd ~/Projects/$1
git init
echo "
# This is my $1 project

This is simply a placeholder readme file
" > README.md
git add -A
git commit -m "Initial README"
gh repo create $1 --confirm --public
git push -u origin master
