#!/bin/bash

usage () {
  echo "$0 <Remote-Branch-Name>"
  exit 1
}


if [[ -z $1 ]]; then
  usage
fi

git pull -t

git fetch
git checkout -t origin/$1
if [ $? ]; then
  git pull
else
  git checkout -b $1
  git push -u origin $1
fi
