#!/usr/bin/env python3

import sys
import common


def usage():
    print(f"{common.f_name} <script-name>")
    exit(1)


if len(sys.argv) < 2:
    usage()

path = sys.argv[1]

common.new_script(path)
