#!/usr/bin/env python3
""" A basic script to genereate new python scripts """

import sys
import Common


def usage():
    """Print the usage info"""
    print(f"{Common.f_name} <script-name>")
    sys.exit(2)


if len(sys.argv) < 2:
    usage()

path = sys.argv[1]

Common.new_script(path)
