#!/usr/bin/env zsh
autoload colors; colors

function traverse() {
  for dir in $1/*
  do
    if [ -d "${dir}" ] ; then
      echo "pulling ${fg[green]}$dir$reset_color"
      cd "$dir"
      git pull
    fi
  done
}

cd ~/.local/bin
echo "pulling ${fg[green]}~/.local/bin$reset_color"
git pull

cd ~/.config
echo "pulling ${fg[green]}~/.config$reset_color"
git pull

cd ~
echo "pulling ${fg[green]}$HOME$reset_color"
git pull

echo "pulling ${fg[green]}Github repos$reset_color"
traverse ~/Projects

~/.config/nvim/install.sh
