#!/bin/bash

usage () {
  echo "$0: creates a new rails project in ~/Documents/Projects/"
  echo "$0 <project_name>"
  exit 1
}

if [[ -z $1 ]]; then
  usage
fi

cd ~/Documents/Projects
rails new $1 --database=postgresql
cd $1
git init
bundle config set without 'production'
git add -A
git commit -m "Initial Commit"
gh repo create
git push -u origin master
heroku create $1
heroku git:remote -a $1
