#!/usr/bin/env zsh
autoload colors; colors

function traverse() {
  for dir in $1/*
  do
    if [ -d "${dir}" ] ; then
      echo "reseting ${fg[green]}$dir$reset_color"
      cd "$dir"
      gitreset
    fi
  done
}

cd ~/.local/bin
echo "reseting ${fg[green]}~/.local/bin$reset_color"
gitreset

cd ~
echo "reseting ${fg[green]}$HOME$reset_color"
gitreset

cd ~/.config
echo "reseting ${fg[green]}~/.config$reset_color"
gitreset
~/.config/nvim/install.sh

echo "reseting ${fg[green]}Github repos$reset_color"
traverse ~/Projects
