#!/bin/bash

rp=$(pwd)

if [[ -n $1 ]]; then
  if grep "alias $1=" ~/.aliases > /dev/null; then
    # set -x
    mv ~/.aliases ~/.aliases.tmp
    sed -e "s;alias $1=.*;alias $1=\"$rp\";" \
      ~/.aliases.tmp > ~/.aliases
    rm ~/.aliases.tmp
    # set +x
  else
    cat >> ~/.aliases <<EOF
alias $1="$rp"
EOF
  fi
else
  cat <<EOF > ~/.restorepath
RP="$rp"
alias rp='source ~/.restorepath && cd \$RP'
source ~/.aliases
EOF
fi
