#!/usr/bin/env python3
from os import chdir
import os.path
import sys
import subprocess
from common import home

f_path, f_name = os.path.split(sys.argv[0])

def usage():
    print(f"{f_name} <Program to add>")
    exit(1)


if len(sys.argv) < 2:
    usage()

setup_path = os.path.join(home, 'Projects', 'pop-setup')

if not os.path.isdir(setup_path):
    subprocess.run(['gclone', 'pop-setup'])

chdir(setup_path)

for app in sys.argv[1:]:
    subprocess.run(['echo', app, '>>', 'apt.packages'], shell=True)

subprocess.run(['sudo', 'apt', 'install', ' '.join(sys.argv[1:])])
