#!/usr/bin/env bash

if [ -d "/Applications/Synergy.app" ]; then
  tmux new-session -s synergy -d '/Applications/Synergy.app/Contents/MacOS/synergys -f'
else
  tmux new-session -s synergy -d 'synergys -f'
fi
