#!/usr/bin/env bash

if [ -d "/Applications/Synergy.app" ]; then
  tmux new-session -s synergy '/Applications/Synergy.app/Contents/MacOS/synergys -f'
else
  tmux new-session -s synergy 'synergys -f'
fi
