#!/usr/bin/env zsh
autoload colors; colors

function traverse() {
  for dir in $1/*
  do
    if [ -d "${dir}" ] ; then
      echo "updating ${fg[green]}$dir$reset_color"
      cd "$dir"
      gitsync 2> /dev/null
    fi
  done
}

cd ~/.local/bin
echo "syncing ${fg[green]}~/.local/bin$reset_color"
gitsync 2> /dev/null

#cd ~/.config
#echo "syncing ${fg[green]}~/.config$reset_color"
#gitsync 2> /dev/null

cd ~
echo "syncing ${fg[green]}$HOME$reset_color"
gitsync 2> /dev/null
rld

echo "syncing ${fg[green]}Github repos$reset_color"
traverse ~/Projects

~/.config/nvim/install.sh
cleanundo
