#!/usr/bin/env zsh
autoload colors; colors

function traverse() {
  for dir in $1/*
  do
    if [ -d "${dir}" ] ; then
      echo "updating ${fg[green]}$dir$reset_color"
      cd "$dir"
      gsync 2> /dev/null
    fi
  done
}

cd ~/.local/bin
echo "syncing ${fg[green]}~/.local/bin$reset_color"
zsh +x gsync 2> /dev/null

cd ~
echo "syncing ${fg[green]}$HOME$reset_color"
gsync 2> /dev/null

cd ~/.config
echo "syncing ${fg[green]}~/.config$reset_color"
gsync 2> /dev/null
~/.config/nvim/install.sh

echo "syncing ${fg[green]}Github repos$reset_color"
traverse ~/Projects

cleanundo
