#!/usr/bin/env python3
""" Sync all system repos using gitui """
import os
import subprocess

from yachalk import chalk

import Common


def traverse(path):
    """ Traverse through all the subdirectories in a path """
    print(f"traversing {chalk.green(path)}")
    for directory in os.listdir(path):
        full_path = path + '/' + directory
        if os.path.isdir(full_path):
            os.chdir(full_path)
            print(f"updating {chalk.green(full_path)}")
            result = subprocess.run(['git', 'status', '-s'],
                                    capture_output=True,
                                    check=True)
            if len(result.stdout) != 0:
                subprocess.run(['gitui'], check=True)


def sync(path: str):
    """ Sync this path """
    os.chdir(path)
    print(f"updating {chalk.green(path)}")
    result = subprocess.run(['git', 'status', '-s'],
                            capture_output=True,
                            check=True)
    if len(result.stdout) != 0:
        subprocess.run(['gitui'], check=True)


home = Common.home or "/home/jhessin"

sync(home + '/.local/bin')

sync(home + '/.config')

sync(home)

print(f"updating {chalk.green('Github repos')}")
traverse(home + '/Projects')

Common.nvim_install()
Common.clean_undo()
