#!/usr/bin/env zsh

yarn set version berry
if [ ! -f "package.json" ]; then
	echo "package.json not found... initializing..."
	yarn init
fi
yarn plugin import @yarnpkg/plugin-typescript
yarn add --dev typescript
yarn dlx @yarnpkg/sdks vim vscode
