#!/usr/bin/env zsh

yarn set version berry
if [ ! -f "package.json" ]; then
	echo "package.json not found... initializing..."
	npm init -y
fi
yarn plugin import @yarnpkg/plugin-typescript
yarn add typescript
echo "nodeLinker: node-modules" >> .yarnrc.yml
yarn
