[package]
name = "gittools"
version = "0.1.0"
authors = ["Jim Hessin <jhessin@gmail.com>"]
edition = "2018"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.12.0"
